# Generated by Django 4.0.6 on 2022-07-11 08:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_employee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('company_strength', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.employer')),
            ],
        ),
    ]
