# Generated by Django 4.0.6 on 2022-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
