# Generated by Django 4.0.6 on 2022-07-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_companygallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygallery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/company/gallery'),
        ),
    ]
