# Generated by Django 4.0.6 on 2022-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_companygallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company/logos'),
        ),
    ]
