# Generated by Django 4.0.6 on 2022-07-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_employerprofile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('5', 'Completed'), ('4', 'On-Hold'), ('6', 'Rejected'), ('1', 'In-Review'), ('3', 'In-Progress'), ('2', 'Shortlist')], max_length=1, null=True),
        ),
    ]
