# Generated by Django 4.0.6 on 2022-07-11 08:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_employee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=200)),
                ('skill', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('maxRole', models.IntegerField(blank=True)),
                ('maxSkil', models.IntegerField(blank=True)),
                ('maxLocation', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('responsibilities', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('qualification_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('skill_experience', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=30, null=True)),
                ('qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, choices=[('1', 'Fresher'), ('2', 'Junior'), ('3', 'Senior'), ('4', 'Mid Carrer'), ('5', 'Executive')], max_length=1)),
                ('tags', models.CharField(blank=True, help_text='comma for new tags', max_length=2000)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship'), ('4', 'Contract')], max_length=1, null=True)),
                ('experince', models.CharField(blank=True, choices=[('2', '2-4 Yrs'), ('3', '5+ Yrs'), ('1', '0-2 Yrs')], max_length=1)),
                ('salary', models.CharField(blank=True, max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('last_date', models.DateField()),
                ('max_round_no', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(blank=True, choices=[('1', 'Drafted'), ('2', 'Active'), ('3', 'Arcived'), ('4', 'Close')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Role', to='jobapp.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employer', to='account.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('2', 'Reject'), ('1', 'Hire'), ('3', 'Hold')], max_length=1)),
                ('round_no', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(blank=True, max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Curate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('workplace', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('news_letter', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('source_of_application', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(blank=True, choices=[('1', 'In-Review'), ('4', 'On-Hold'), ('5', 'Completed'), ('3', 'In-Progress'), ('2', 'Shortlist'), ('6', 'Rejected')], max_length=1)),
                ('final_status', models.CharField(blank=True, choices=[('2', 'Reject'), ('1', 'Hire')], max_length=1)),
                ('followup_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('followup_status', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
    ]
