# Generated by Django 4.0.6 on 2022-07-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurateData',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='final_status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Shortlist'), ('5', 'Completed'), ('3', 'In-Progress'), ('1', 'In-Review'), ('6', 'Rejected'), ('4', 'On-Hold')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('2', 'Reject'), ('3', 'Hold')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('1', '0-2 Yrs'), ('2', '2-4 Yrs'), ('3', '5+ Yrs')], max_length=1),
        ),
    ]
