# Generated by Django 4.0.6 on 2022-07-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_delete_curatedata_alter_applicant_final_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Shortlist'), ('6', 'Rejected'), ('5', 'Completed'), ('3', 'In-Progress'), ('1', 'In-Review'), ('4', 'On-Hold')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('3', 'Hold'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('3', '5+ Yrs'), ('1', '0-2 Yrs'), ('2', '2-4 Yrs')], max_length=1),
        ),
    ]
