# Generated by Django 4.0.6 on 2022-07-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_applicant_status_alter_interview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='final_status',
            field=models.CharField(blank=True, choices=[('2', 'Reject'), ('1', 'Hire')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('5', 'Completed'), ('1', 'In-Review'), ('6', 'Rejected'), ('3', 'In-Progress'), ('2', 'Shortlist'), ('4', 'On-Hold')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Reject'), ('3', 'Hold'), ('1', 'Hire')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('1', '0-2 Yrs'), ('3', '5+ Yrs'), ('2', '2-4 Yrs')], max_length=1),
        ),
    ]
