# Generated by Django 4.0.6 on 2022-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_applicant_status_alter_interview_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_place',
            field=models.CharField(blank=True, choices=[('1', 'Remote'), ('2', 'Hybrid'), ('3', 'On-Site')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Shortlist'), ('4', 'On-Hold'), ('3', 'In-Progress'), ('1', 'In-Review'), ('5', 'Completed'), ('6', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('3', 'Hold'), ('2', 'Reject'), ('1', 'Hire')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('1', '0-2 Yrs'), ('3', '5+ Yrs'), ('2', '2-4 Yrs')], max_length=1),
        ),
    ]
