# Generated by Django 4.0.6 on 2022-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_job_work_place_alter_applicant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bonus',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'High Distinction'), ('2', 'Distinction'), ('3', 'Credit'), ('4', 'Pass')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='relocation',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.CharField(blank=True, help_text='comma for new tags', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stock',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='visa',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_hour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'In-Review'), ('3', 'In-Progress'), ('4', 'On-Hold'), ('6', 'Rejected'), ('2', 'Shortlist'), ('5', 'Completed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('1', '0-2 Yrs'), ('2', '2-4 Yrs'), ('3', '5+ Yrs')], max_length=1),
        ),
    ]
