# Generated by Django 4.0.6 on 2022-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_job_bonus_job_grade_job_relocation_job_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='final_status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('3', 'In-Progress'), ('5', 'Completed'), ('4', 'On-Hold'), ('2', 'Shortlist'), ('1', 'In-Review'), ('6', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('3', 'Hold'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('3', '5+ Yrs'), ('2', '2-4 Yrs'), ('1', '0-2 Yrs')], max_length=1),
        ),
    ]
