# Generated by Django 4.0.6 on 2022-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_interview_second_status_alter_applicant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('3', 'In-Progress'), ('5', 'Completed'), ('2', 'Shortlist'), ('1', 'In-Review'), ('4', 'On-Hold'), ('6', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('3', '5+ Yrs'), ('2', '2-4 Yrs'), ('1', '0-2 Yrs')], max_length=1),
        ),
    ]
