# Generated by Django 4.0.6 on 2022-07-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_interview_title_alter_applicant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('3', 'In-Progress'), ('6', 'Rejected'), ('1', 'In-Review'), ('2', 'Shortlist'), ('5', 'Completed'), ('4', 'On-Hold')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('2', '2-4 Yrs'), ('1', '0-2 Yrs'), ('3', '5+ Yrs')], max_length=1),
        ),
    ]
