# Generated by Django 4.0.6 on 2022-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_interview_interview_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='final_status',
            field=models.CharField(blank=True, choices=[('2', 'Reject'), ('1', 'Hire')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('4', 'On-Hold'), ('6', 'Rejected'), ('5', 'Completed'), ('3', 'In-Progress'), ('2', 'Shortlist'), ('1', 'In-Review')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='second_status',
            field=models.CharField(blank=True, choices=[('2', 'Failed'), ('1', 'Passed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Reject'), ('3', 'Hold'), ('1', 'Hire')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('1', '0-2 Yrs'), ('2', '2-4 Yrs'), ('3', '5+ Yrs')], max_length=1),
        ),
    ]
