# Generated by Django 4.0.6 on 2022-07-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_mobile'),
        ('jobapp', '0013_alter_applicant_status_alter_interview_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='qualification_details',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_experience',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='final_status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'In-Review'), ('5', 'Completed'), ('3', 'In-Progress'), ('4', 'On-Hold'), ('2', 'Shortlist'), ('6', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('3', 'Hold'), ('2', 'Reject')], max_length=1),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('profeciency', models.CharField(blank=True, choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advance')], max_length=1, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employer')),
            ],
        ),
    ]
