# Generated by Django 4.0.6 on 2022-07-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_alter_applicant_status_alter_interview_second_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('5', 'Completed'), ('4', 'On-Hold'), ('6', 'Rejected'), ('1', 'In-Review'), ('3', 'In-Progress'), ('2', 'Shortlist')], max_length=1),
        ),
    ]
