# Generated by Django 4.0.6 on 2022-07-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_alter_applicant_final_status_alter_applicant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('3', 'In-Progress'), ('4', 'On-Hold'), ('5', 'Completed'), ('6', 'Rejected'), ('1', 'In-Review'), ('2', 'Shortlist')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='second_status',
            field=models.CharField(blank=True, choices=[('2', 'Reject'), ('1', 'Passed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('3', 'Hold'), ('1', 'Hire'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('1', '0-2 Yrs'), ('2', '2-4 Yrs'), ('3', '5+ Yrs')], max_length=1),
        ),
    ]
