# Generated by Django 4.0.6 on 2022-07-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_alter_applicant_final_status_alter_applicant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Shortlist'), ('3', 'In-Progress'), ('1', 'In-Review'), ('4', 'On-Hold'), ('6', 'Rejected'), ('5', 'Completed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('1', '0-2 Yrs'), ('3', '5+ Yrs'), ('2', '2-4 Yrs')], max_length=1),
        ),
    ]
