# Generated by Django 4.0.6 on 2022-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_alter_applicant_status_alter_job_experince'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='final_status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('4', 'On-Hold'), ('5', 'Completed'), ('1', 'In-Review'), ('6', 'Rejected'), ('3', 'In-Progress'), ('2', 'Shortlist')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='second_status',
            field=models.CharField(blank=True, choices=[('3', 'On-Hold'), ('1', 'Passed'), ('2', 'Reject')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Hire'), ('2', 'Reject'), ('3', 'Hold')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('3', '5+ Yrs'), ('2', '2-4 Yrs'), ('1', '0-2 Yrs')], max_length=1),
        ),
    ]
