# Generated by Django 4.0.6 on 2022-07-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0026_alter_applicant_final_status_alter_applicant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='final_status',
            field=models.CharField(blank=True, choices=[('2', 'Reject'), ('1', 'Hire')], max_length=1),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Shortlist'), ('5', 'Completed'), ('4', 'On-Hold'), ('3', 'In-Progress'), ('1', 'In-Review'), ('6', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='second_status',
            field=models.CharField(blank=True, choices=[('1', 'Passed'), ('2', 'Reject'), ('3', 'On-Hold')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('2', 'Reject'), ('3', 'Hold'), ('1', 'Hire')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='experince',
            field=models.CharField(blank=True, choices=[('2', '2-4 Yrs'), ('1', '0-2 Yrs'), ('3', '5+ Yrs')], max_length=1),
        ),
    ]
